package visualization.visualizer;

import visualization.event.*;

/**
 * VisualizerXY is an abstract base class for all applications that
 * visualize XY-Plot data that is generated by a {@link visualization.generator.Generator}.
 *
 * @author		Roelof Kemp
 * @version		0.1
 **/
public abstract class VisualizerXY extends Visualizer {

	/**
	 * Sets the interval between measurements of the Visualizer.
	 * A {@link visualization.event.IntervalEvent} is sent to the Generator
	 *
	 * @param interval the interval in ms
	 */
	public void setInterval(String source, int interval) {
		sendEvent(new IntervalEvent(source, interval));
	}


	/**
	 * Enables or disables a source
	 * A {@link visualization.event.EnableEvent} is sent to the Generator
	 *
	 */
	public void setEnabled(String source, boolean enabled) {
		sendEvent(new EnableEvent(source, enabled));
	}

	/**
	 * Starts the visualization.
	 * A {@link visualization.event.StartEvent} is sent to the Generator
	 */
	public void startGenerator() {
		sendEvent(new StartEvent());
	}

}
