package visualization.event;

/**
 * Basic event. Events are generated by a {@link visualization.visualizer.Visualizer} and are send to a {@link visualization.generator.Generator}.
 *
 * @author		Roelof Kemp
 * @version		0.1
 **/
public class Event implements java.io.Serializable {
	private String eventString;

	/**
	 * Constructs an <code>Event</code> with the specified event string
	 *
	 * @param eventString	a string representation of the event
	 */
	public Event(String eventString) {
		this.eventString = eventString;
	}

	/**
	 * Gets the event string
	 * 
	 * @return the string representation of the event
	 */
	public String getEventString() {
		return eventString;
	}
}
